# Generated by Django 3.1.3 on 2021-01-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
